import os
from pptx import Presentation
from pptx.util import Pt
from pptx.dml.color import RGBColor
from pptx.parts.image import Image
from utils.logger import get_logger

logger = get_logger()

class PPTGenerator:
    def __init__(self, template_path=None):
        self.template_path = template_path

    def generate(self, items, output_path, title="Exam Paper", expected_question_count=None):
        try:
            if self.template_path and os.path.exists(self.template_path):
                prs = Presentation(self.template_path)
            else:
                prs = Presentation()
            self._add_cover_slide(prs, title)
            for item in items:
                item_type = item.get("type", "question")
                if item_type == "context":
                    self._add_context_slides(prs, item.get("content", ""))
                elif item_type == "question":
                    self._add_question_slides(prs, item)
                else:
                    if "question" in item:
                        self._add_question_slides(prs, item)
            output_dir = os.path.dirname(output_path)
            if output_dir and not os.path.exists(output_dir):
                os.makedirs(output_dir)
            prs.save(output_path)
            logger.info(f"PPT saved successfully at: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to generate PPT: {e}")
            raise

    def _add_cover_slide(self, prs, title):
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        title_shape.text = title
        subtitle_shape.text = "Generated by Exam2PPT"

    def _add_question_slides(self, prs, question_data):
        q_id = question_data.get("id", "")
        question_text = question_data.get("question", "")
        options = question_data.get("options", [])
        answer = question_data.get("answer", "")
        analysis = question_data.get("analysis", "")
        images = question_data.get("images", [])

        question_chunks = self._split_text(question_text)
        for i, chunk in enumerate(question_chunks):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            title_shape = slide.shapes.title
            if len(question_chunks) > 1:
                title_shape.text = f"Question {q_id} ({i+1}/{len(question_chunks)})"
            else:
                title_shape.text = f"Question {q_id}"
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(28)
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            p = tf.add_paragraph()
            p.text = chunk
            p.font.bold = True
            p.font.size = Pt(self._font_size(chunk))
            if i == len(question_chunks) - 1:
                for opt in options:
                    p = tf.add_paragraph()
                    p.text = opt
                    p.font.size = Pt(20)
            if images and i == 0:
                self._add_images(prs, slide, body_shape, images)

        analysis_chunks = self._split_text(analysis) if analysis else [""]
        for i, chunk in enumerate(analysis_chunks):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            title_shape = slide.shapes.title
            if len(analysis_chunks) > 1:
                title_shape.text = f"Answer {q_id} ({i+1}/{len(analysis_chunks)})"
            else:
                title_shape.text = f"Answer {q_id}"
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(28)
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            if i == 0:
                p = tf.add_paragraph()
                p.text = f"Correct Answer: {answer}"
                p.font.bold = True
                p.font.size = Pt(24)
                p.font.color.rgb = RGBColor(0, 0, 0)
            if chunk:
                p = tf.add_paragraph()
                p.text = chunk
                p.font.size = Pt(self._font_size(chunk))

    def _add_context_slides(self, prs, context_text):
        chunks = self._split_text(context_text)
        total = len(chunks)
        for i, chunk in enumerate(chunks):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            title_shape = slide.shapes.title
            if total > 1:
                title_shape.text = f"Background Material ({i+1}/{total})"
            else:
                title_shape.text = "Background Material"
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(28)
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            p = tf.add_paragraph()
            p.text = chunk
            p.font.size = Pt(self._font_size(chunk))
            p.font.color.rgb = RGBColor(50, 50, 50)

    def _split_text(self, text):
        if not text:
            return [""]
        if len(text) <= 500:
            return [text]
        mid = len(text) // 2
        window = 80
        separators = "\n。？！.!?；;，,"
        split_at = None
        for offset in range(window):
            left = mid - offset
            right = mid + offset
            if left > 0 and text[left] in separators:
                split_at = left + 1
                break
            if right < len(text) and text[right] in separators:
                split_at = right + 1
                break
        if not split_at:
            split_at = mid
        part1 = text[:split_at].strip()
        part2 = text[split_at:].strip()
        return [part1, part2]

    def _font_size(self, text):
        return 16 if len(text) > 200 else 24

    def _add_images(self, prs, slide, body_shape, images):
        slide_width = prs.slide_width
        slide_height = prs.slide_height
        body_shape.width = int(slide_width * 0.6)
        left = int(slide_width * 0.62)
        top = int(slide_height * 0.18)
        max_width = int(slide_width * 0.34)
        max_height = int(slide_height * 0.64)
        for img_path in images:
            if os.path.exists(img_path):
                self._add_picture_fit(slide, img_path, left, top, max_width, max_height)
                break

    def _add_picture_fit(self, slide, path, left, top, max_width, max_height):
        try:
            image = Image.from_file(path)
            width_px, height_px = image.size
            dpi_x, dpi_y = image.dpi if image.dpi else (96, 96)
            dpi_x = dpi_x or 96
            dpi_y = dpi_y or 96
            emu_per_inch = 914400
            width_emu = int(width_px / dpi_x * emu_per_inch)
            height_emu = int(height_px / dpi_y * emu_per_inch)
            scale = min(max_width / width_emu, max_height / height_emu, 1.0)
            draw_w = int(width_emu * scale)
            draw_h = int(height_emu * scale)
            slide.shapes.add_picture(path, left, top, width=draw_w, height=draw_h)
        except Exception as e:
            logger.warning(f"Image fit failed: {e}")
            slide.shapes.add_picture(path, left, top, width=max_width, height=max_height)
