import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from utils.logger import get_logger

logger = get_logger()

from tkinter import messagebox

class PPTGenerator:
    """
    Generates PowerPoint slides from structured question data.
    """
    def __init__(self, template_path=None):
        self.template_path = template_path

    def generate(self, items, output_path, title="Exam Paper", expected_question_count=None):
        """
        Generates the PPT file.
        
        Args:
            items (list): List of dictionaries (questions or context).
            output_path (str): Path to save the PPTX file.
            title (str): Title for the cover slide.
            expected_question_count (int): Optional watchdog counter for verification.
        """
        try:
            # Count actual questions for watchdog
            actual_count = sum(1 for item in items if item.get('type') == 'question')
            logger.info(f"Starting PPT generation for {len(items)} items ({actual_count} questions)...")
            
            # Watchdog Verification
            if expected_question_count and expected_question_count > 0:
                diff = abs(expected_question_count - actual_count)
                # Allow small margin of error (e.g., regex might miss 1-2, or AI might merge 1-2)
                if diff > 2: 
                    logger.warning(f"[Watchdog Alert] Input count ({expected_question_count}) != Output count ({actual_count})")
            
            if self.template_path and os.path.exists(self.template_path):
                prs = Presentation(self.template_path)
            else:
                prs = Presentation() # Uses default blank template

            # 1. Create Cover Slide
            self._add_cover_slide(prs, title)

            # 2. Process each item
            for item in items:
                item_type = item.get('type', 'question') # Default to question for backward compatibility if needed
                
                if item_type == 'context':
                    self._add_context_slides(prs, item.get('content', ''))
                elif item_type == 'question':
                    self._add_question_slides(prs, item)
                else:
                    # Fallback for old format or unknown types, treat as question if it has 'question' field
                    if 'question' in item:
                        self._add_question_slides(prs, item)

            # 3. Save
            # Ensure directory exists
            output_dir = os.path.dirname(output_path)
            if output_dir and not os.path.exists(output_dir):
                os.makedirs(output_dir)
                
            prs.save(output_path)
            logger.info(f"PPT saved successfully at: {output_path}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to generate PPT: {e}")
            raise

    def _add_cover_slide(self, prs, title):
        """Adds a title slide."""
        # Layout 0 is usually Title Slide
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        
        title_shape.text = title
        subtitle_shape.text = "Generated by Exam2PPT"

    def _add_question_slides(self, prs, question_data):
        """
        Adds slides for a single question.
        - Adds Question + Options on a separate slide.
        - Adds Answer + Analysis on a separate slide.
        """
        # Extract data
        q_id = question_data.get('id', '')
        # q_type = question_data.get('type', '') # 'type' is now used for item type distinction (context vs question)
        # But wait, the LLM prompt says question object has 'type': 'question'.
        # The prompt ALSO asked for 'type' (题型) inside the object previously?
        # Let's check the prompt again.
        # New prompt: "题目对象"：`{ "type": "question", "id": "题号", "question": "...", ... }`
        # It seems I removed the "题型" field (Choice/Fill) from the prompt to simplify.
        # If I need 题型, I should have kept it.
        # The prompt says: "id", "type" (literal "question"), "question", ...
        # So "type" is "question".
        # If the user wants to know if it's Choice or Fill, it might be in the title or content.
        # For now, I'll ignore "q_type" display or just use "Question {q_id}".
        
        question_text = question_data.get('question', '')
        options = question_data.get('options', [])
        answer = question_data.get('answer', '')
        analysis = question_data.get('analysis', '')

        # --- Part 1: Question Slide ---
        # Layout 1 is usually Title and Content
        slide_layout = prs.slide_layouts[1] 
        slide = prs.slides.add_slide(slide_layout)
        
        # Title
        title_shape = slide.shapes.title
        title_shape.text = f"Question {q_id}"
        # Reduce title font size
        if title_shape.text_frame:
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(28)
        
        # Content Body
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()  # Clear default empty paragraph

        # Add Question
        p = tf.add_paragraph()
        p.text = question_text
        p.font.bold = True
        p.font.size = Pt(22)
        p.space_before = Pt(6)

        # Add Options
        if options:
            for opt in options:
                p = tf.add_paragraph()
                p.text = opt
                p.font.size = Pt(20)
                p.level = 0 # No indent or small indent
                p.space_before = Pt(6)

        # Add Images (if any)
        images = question_data.get('images', [])
        if images:
            # Simple layout: Add images at the bottom or right
            # For simplicity, we add them to the right side if there's space, or create a new slide if needed.
            # Let's try to add them to the current slide first, scaling them down.
            
            # Get slide width/height
            slide_width = prs.slide_width
            slide_height = prs.slide_height
            
            # Position for image: Right side, centered vertically?
            # Or below text?
            # Let's put it on the right side.
            # Resize text frame to 60% width
            body_shape.width = int(slide_width * 0.6)
            
            img_left = int(slide_width * 0.65)
            img_top = int(slide_height * 0.2)
            img_height = int(slide_height * 0.6)
            
            for img_path in images:
                if os.path.exists(img_path):
                    try:
                        # Add picture
                        pic = slide.shapes.add_picture(img_path, img_left, img_top, height=img_height)
                        # Only add one image per slide for now to avoid overlap
                        # If multiple images, maybe add multiple slides?
                        # For now, just the first one.
                        break 
                    except Exception as e:
                        logger.error(f"Failed to add image {img_path}: {e}")

        # --- Part 2: Answer & Analysis Slide ---
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        
        title_shape = slide.shapes.title
        title_shape.text = f"Answer {q_id}"
        # Reduce title font size
        if title_shape.text_frame:
            for paragraph in title_shape.text_frame.paragraphs:
                paragraph.font.size = Pt(28)
        
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()

        # Add Answer
        p = tf.add_paragraph()
        run = p.add_run()
        run.text = f"Correct Answer: {answer}"
        run.font.bold = True
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(0, 0, 0) # Black (Fixed: Removed Red)

        # Add Analysis
        if analysis:
            # Check for overflow
            if len(analysis) > 300:
                self._add_long_analysis_slides(prs, analysis, q_id)
            else:
                p = tf.add_paragraph()
                p.text = "\n[Analysis]"
                p.font.bold = True
                p.font.size = Pt(20)
                
                p = tf.add_paragraph()
                p.text = analysis
                p.font.size = Pt(18)

    def _add_long_analysis_slides(self, prs, analysis_text, q_id):
        """
        Handles long analysis by splitting into multiple slides.
        Uses a stricter 300 chars limit per slide to avoid overflow.
        """
        chunk_size = 300 # Reduced from 500
        chunks = [analysis_text[i:i+chunk_size] for i in range(0, len(analysis_text), chunk_size)]
        
        for i, chunk in enumerate(chunks):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            
            title_shape = slide.shapes.title
            title_shape.text = f"Answer {q_id} (Analysis {i+1}/{len(chunks)})"
            if title_shape.text_frame:
                for p in title_shape.text_frame.paragraphs:
                    p.font.size = Pt(24) # Fixed title size
            
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            
            p = tf.add_paragraph()
            p.text = chunk
            p.font.size = Pt(18) # Fixed body size

    def _add_context_slides(self, prs, context_text):
        """
        Splits context text into multiple slides if too long.
        """
        # Heuristic: Reduced to 400 chars to prevent overflow
        chunk_size = 400 
        chunks = [context_text[i:i+chunk_size] for i in range(0, len(context_text), chunk_size)]
        
        total_chunks = len(chunks)
        for i, chunk in enumerate(chunks):
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            
            title_shape = slide.shapes.title
            if total_chunks > 1:
                title_shape.text = f"Background Material ({i+1}/{total_chunks})"
            else:
                title_shape.text = f"Background Material"
            
            # Reduce title font size
            if title_shape.text_frame:
                for paragraph in title_shape.text_frame.paragraphs:
                    paragraph.font.size = Pt(28) # Fixed title size
            
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()
            
            p = tf.add_paragraph()
            p.text = chunk
            p.font.size = Pt(18) # Fixed body size
            p.font.color.rgb = RGBColor(50, 50, 50)
            p.alignment = PP_ALIGN.LEFT

if __name__ == "__main__":
    # Test block
    pass
